const games = [
  {
    id: 1,
    title: "Black Myth: Wukong",
    price: 1300000,
    oldPrice: 1500000,
    img: "img/background/BlackWukong.jpg",
    screenshots: [
      "img/blackmyth/wukong-1.jpg",
      "img/blackmyth/wukong-2.jpg",
      "img/blackmyth/wukong-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "Game Science",
    publisher: "Game Science",
    releaseDate: "2024-08-20",
    description:
      "Hóa thân thành Tôn Ngộ Không trong siêu phẩm hành động nhập vai.",
    trailer: "Wl05yGSDpxY",
  },
  {
    id: 2,
    title: "Elden Ring",
    price: 900000,
    oldPrice: 1100000,
    img: "img/background/EldenRing.jpg",
    screenshots: [
      "img/eldenring/er-1.jpg",
      "img/eldenring/er-2.jpg",
      "img/eldenring/er-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    description: "Khám phá Lands Between và trở thành Elden Lord.",
    trailer: "K_03kFqWfqs",
  },
  {
    id: 3,
    title: "Stray",
    price: 300000,
    oldPrice: 350000,
    img: "img/background/Stray.jpg",
    screenshots: [
      "img/stray/stray-1.jpg",
      "img/stray/stray-2.jpg",
      "img/stray/stray-3.jpg",
    ],
    categories: ["Indie", "Adventure"],
    developer: "BlueTwelve Studio",
    publisher: "Annapurna Interactive",
    releaseDate: "2022-07-19",
    description: "Trải nghiệm cuộc sống của mèo trong thế giới cyberpunk.",
    trailer: "kJawWyRUOBM",
  },
  {
    id: 4,
    title: "Cyberpunk 2077",
    price: 800000,
    oldPrice: 1600000,
    img: "img/background/Cyber2077.jpg",
    screenshots: [
      "img/cyberpunk/cyber-1.jpg",
      "img/cyberpunk/cyber-2.jpg",
      "img/cyberpunk/cyber-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2020-12-10",
    description: "Phiêu lưu hành động thế giới mở tại Night City.",
    trailer: "8X2kIfS6fb8",
  },
  {
    id: 5,
    title: "Resident Evil 4 Remake",
    price: 950000,
    oldPrice: 1200000,
    img: "img/background/Re4RK.jpg",
    screenshots: [
      "img/re4r/re4-1.jpg",
      "img/re4r/re4-2.jpg",
      "img/re4r/re4-3.jpg",
    ],
    categories: ["Horror", "Action"],
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2023-03-24",
    description: "Bản remake của huyền thoại kinh dị sinh tồn.",
    trailer: "Id2EaldBaWw",
  },
  {
    id: 6,
    title: "God of War Ragnarök",
    price: 1200000,
    oldPrice: 1500000,
    img: "img/background/GodOfWarR.jpg",
    screenshots: [
      "img/godofwar/gow-1.jpg",
      "img/godofwar/gow-2.jpg",
      "img/godofwar/gow-3.jpg",
    ],
    categories: ["Action", "Adventure"],
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2022-11-09",
    description: "Kratos và Atreus đối mặt Ragnarök.",
    trailer: "hfJ4Km46A-0",
  },
  {
    id: 7,
    title: "Sekiro: Shadows Die Twice",
    price: 750000,
    oldPrice: 1000000,
    img: "img/background/Sekiro.jpg",
    screenshots: [
      "img/sekiro/sekiro-1.jpg",
      "img/sekiro/sekiro-2.jpg",
      "img/sekiro/sekiro-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "FromSoftware",
    publisher: "Activision",
    releaseDate: "2019-03-22",
    description: "Chặt chém siêu khó phong cách Nhật Bản.",
    trailer: "rXMX4YJ7Lks",
  },
  {
    id: 8,
    title: "Red Dead Redemption 2",
    price: 850000,
    oldPrice: 1200000,
    img: "img/background/RDR2.jpg",
    screenshots: [
      "img/red-dead/rdr2-1.jpg",
      "img/red-dead/rdr2-2.jpg",
      "img/red-dead/rdr2-3.jpg",
    ],
    categories: ["Open World", "Action"],
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "2018-10-26",
    description: "Cuộc sống cao bồi trong thế giới mở.",
    trailer: "gmA6MrX81z4",
  },
  {
    id: 9,
    title: "Hogwarts Legacy",
    price: 900000,
    oldPrice: 1300000,
    img: "img/background/Harry.jpg",
    screenshots: [
      "img/hogwartL/hl-1.jpg",
      "img/hogwartL/hl-2.jpg",
      "img/hogwartL/hl-3.jpg",
    ],
    categories: ["RPG", "Adventure"],
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    releaseDate: "2023-02-10",
    description: "Khám phá Hogwarts thế kỷ 19.",
    trailer: "1O6Qstncpnc",
  },
  {
    id: 10,
    title: "Monster Hunter World",
    price: 600000,
    oldPrice: 900000,
    img: "img/background/monster.jpg",
    screenshots: [
      "img/monster/monster-1.jpg",
      "img/monster/monster-2.jpg",
      "img/monster/monster-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2018-01-26",
    description: "Săn quái vật cùng bạn bè.",
    trailer: "7paWNhKkX38",
  },
  {
    id: 11,
    title: "Dark Souls III",
    price: 700000,
    oldPrice: 1000000,
    img: "img/background/DS3.jpg",
    screenshots: [
      "img/darksoul3/ds3-1.jpg",
      "img/darksoul3/ds3-2.jpg",
      "img/darksoul3/ds3-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2016-04-12",
    description: "Thế giới tăm tối và độ khó huyền thoại.",
    trailer: "cWBwFhUv1-8",
  },
  {
    id: 12,
    title: "The Witcher 3: Wild Hunt",
    price: 650000,
    oldPrice: 1100000,
    img: "img/background/WC3.jpg",
    screenshots: [
      "img/witcher3/witcher3-1.jpg",
      "img/witcher3/witcher3-2.jpg",
      "img/witcher3/witcher3-3.jpg",
    ],
    categories: ["RPG", "Open World"],
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2015-05-19",
    description: "Theo chân Geralt trong hành trình săn quái.",
    trailer: "53MyR_Z3i1w",
  },
  {
    id: 13,
    title: "GTA V",
    price: 500000,
    oldPrice: 800000,
    img: "img/background/Grand-Theft-Auto-V.jpg",
    screenshots: [
      "img/gta5/gta5-1.jpg",
      "img/gta5/gta5-2.jpg",
      "img/gta5/gta5-3.jpg",
    ],
    categories: ["Open World", "Action"],
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    releaseDate: "2013-09-17",
    description: "Thế giới mở hỗn loạn tại Los Santos.",
    trailer: "QkkoHAzjnUs",
  },
  {
    id: 14,
    title: "Devil May Cry 5",
    price: 700000,
    oldPrice: 1000000,
    img: "img/background/devil-may-cry-5.jpg",
    screenshots: [
      "img/dmc5/dmc-1.jpg",
      "img/dmc5/dmc-2.jpg",
      "img/dmc5/dmc-3.jpg",
    ],
    categories: ["Action", "Hack and Slash"],
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2019-03-08",
    description: "Chặt chém mãn nhãn cùng Dante và Vergil.",
    trailer: "dG6_CAdiLPM",
  },
  {
    id: 15,
    title: "Assassin's Creed Valhalla",
    price: 800000,
    oldPrice: 1300000,
    img: "img/background/Assasin.jpg",
    screenshots: [
      "img/assasin/assasin-1.jpg",
      "img/assasin/assasin-2.jpg",
      "img/assasin/assasin-3.jpg",
    ],
    categories: ["Action", "RPG"],
    developer: "Ubisoft Montreal",
    publisher: "Ubisoft",
    releaseDate: "2020-11-10",
    description: "Chiến binh Viking trong Bắc Âu.",
    trailer: "ssrNcwxALS4",
  },
  {
    id: 16,
    title: "Death Stranding",
    price: 650000,
    oldPrice: 1000000,
    img: "img/background/DST.jpg",
    screenshots: [
      "img/deathstrange/ds-1.jpg",
      "img/deathstrange/ds-2.jpg",
      "img/deathstrange/ds-3.jpg",
    ],
    categories: ["Adventure", "Action"],
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2019-11-08",
    description: "Trải nghiệm độc lạ đậm chất Kojima.",
    trailer: "Mpn-MC2B6Zc",
  },
  {
    id: 17,
    title: "DOOM Eternal",
    price: 700000,
    oldPrice: 1000000,
    img: "img/background/doom.jpg",
    screenshots: [
      "img/doom/doom-1.jpg",
      "img/doom/doom-2.jpg",
      "img/doom/doom-3.jpg",
    ],
    categories: ["FPS", "Action"],
    developer: "id Software",
    publisher: "Bethesda Softworks",
    releaseDate: "2020-03-20",
    description: "Bắn quỷ tốc độ cao, máu lửa.",
    trailer: "_UuktemkCFI",
  },
  {
    id: 18,
    title: "Starfield",
    price: 1100000,
    oldPrice: 1400000,
    img: "img/background/starfield-cover.jpg",
    screenshots: [
      "img/starfield/star-1.jpg",
      "img/starfield/star-2.jpg",
      "img/starfield/star-3.jpg",
    ],
    categories: ["RPG", "Sci-Fi"],
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    releaseDate: "2023-09-06",
    description: "Khám phá vũ trụ rộng lớn.",
    trailer: "kfYEiTdsyas",
  },
  {
    id: 19,
    title: "Baldur's Gate 3",
    price: 950000,
    oldPrice: 1200000,
    img: "img/background/Baldurs-Gate-3-header-scaled.jpg",
    screenshots: [
      "img/baldur/baldur-1.jpg",
      "img/baldur/baldur-2.jpg",
      "img/baldur/baldur-3.jpg",
    ],
    categories: ["RPG", "Strategy"],
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    description: "Nhập vai chiến thuật theo luật D&D.",
    trailer: "WvMf_DcyWbI",
  },
  {
    id: 20,
    title: "Hades",
    price: 350000,
    oldPrice: 500000,
    img: "img/background/hades.jpg",
    screenshots: [
      "img/hades/hades-1.jpg",
      "img/hades/hades-2.jpg",
      "img/hades/hades-3.jpg",
    ],
    categories: ["Indie", "Roguelike"],
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseDate: "2020-09-17",
    description: "Roguelike chặt chém cuốn khỏi nói.",
    trailer: "91t0ha9x0AE",
  },
  {
    id: 21,
    title: "Dead Space Remake",
    price: 900000,
    oldPrice: 1200000,
    img: "img/background/dead-space-remake.jpg",
    screenshots: [
      "img/deadspace/deadspace-1.jpg",
      "img/deadspace/deadspace-2.jpg",
      "img/deadspace/deadspace-3.jpg",
    ],
    categories: ["Horror", "Sci-Fi"],
    developer: "Motive Studio",
    publisher: "Electronic Arts",
    releaseDate: "2023-01-27",
    description: "Kinh dị không gian nghẹt thở.",
    trailer: "ctQl9wa3ydE",
  },
  {
    id: 22,
    title: "Resident Evil 9: Requiem",
    price: 1300000,
    oldPrice: 1500000,
    img: "img/background/RE9.jpg",
    screenshots: [
      "img/re9/re9-1.jpg",
      "img/re9/re9-2.jpg",
      "img/re9/re9-3.jpg",
    ],
    categories: ["Horror", "Action"],
    developer: "Capcom",
    publisher: "Capcom",
    releaseDate: "2026-01-01",
    description: "Leon S. Kennedy trở lại Raccoon City.",
    trailer: "T54OWinnymM",
  },
  {
    id: 23,
    title: "Alan Wake 2",
    price: 950000,
    oldPrice: 1200000,
    img: "img/background/alan-wake-2.jpg",
    screenshots: [
      "img/alanwake/alanwake-1.jpg",
      "img/alanwake/alanwake-2.jpg",
      "img/alanwake/alanwake-3.jpg",
    ],
    categories: ["Horror", "Adventure"],
    developer: "Remedy Entertainment",
    publisher: "Epic Games Publishing",
    releaseDate: "2023-10-27",
    description: "Kinh dị tâm lý xoắn não.",
    trailer: "dlQ3FeNu5Yw",
  },
  {
    id: 24,
    title: "Ghost of Tsushima",
    price: 850000,
    oldPrice: 1200000,
    img: "img/background/GOT.jpg",
    screenshots: [
      "img/got/got-1.jpg",
      "img/got/got-2.jpg",
      "img/got/got-3.jpg",
    ],
    categories: ["Action", "Adventure"],
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2020-07-17",
    description: "Samurai bảo vệ đảo Tsushima.",
    trailer: "RcWk08PBe7k",
  },
  {
    id: 25,
    title: "Hoa",
    price: 250000,
    oldPrice: 350000,
    img: "img/background/hoa.jpg",
    screenshots: [
      "img/hoa/hoa-1.jpg",
      "img/hoa/hoa-2.jpg",
      "img/hoa/hoa-3.jpg",
    ],
    categories: ["Indie", "Adventure"],
    developer: "Skrollcat Studio",
    publisher: "PM Studios",
    releaseDate: "2021-08-24",
    description:
      "Tựa game phiêu lưu giải đố mang phong cách nghệ thuật vẽ tay, kể câu chuyện nhẹ nhàng về thiên nhiên và sự chữa lành.",
    trailer: "MlBjHUdgaZw",
  },
];
